### ISSUE TITLE
The jvm_threads_daemon_threads indicator will gradually become negative

### ISSUE THREAD

**Issue by liuxuzxx** [grafana/pyroscope-java#203]
We introduced pyroscope.jar as an agent. After the process worked for about 20 minutes, we found that the jvm_threads_daemon_thread indicator obtained from spring-boot-actuator gradually changed from positive to negative. When we removed the pyroscope.jar agent, we found that it was normal.

![Image](https://github.com/user-attachments/assets/e751e640-157b-4109-bf27-8d26a4e35127)

**Comment by liuxuzxx** [comment]
The first three monitoring data in this figure are configured with pyroscope.jar as the agent. It can be seen that the jvm_threads_daemon_thread indicator shows a linear function property, gradually decreasing to a negative number. The last book removes pyroscope.jar as the agent monitoring, and it is normal.

**Comment by liuxuzxx** [comment]
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpaas-msg-hub-deployment
spec:
  template:
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                ......
                -javaagent:/skywalking/agent/skywalking-agent.jar
                -javaagent:/shared-data/pyroscope/pyroscope.jar #use -javaagent
                -Dcom.rocketmq.remoting.client.worker.size="10"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SW_AGENT_NAME
              value: cpaas-msg-hub
            - name: PYROSCOPE_AGENT_ENABLED
              value: 'true'
            - name: PYROSCOPE_APPLICATION_NAME
              value: cpaas-msg-hub
            - name: PYROSCOPE_PROFILING_INTERVAL
              value: 30ms
            - name: PYROSCOPE_FORMAT
              value: jfr
            - name: PYROSCOPE_PROFILER_EVENT
              value: itimer
            - name: PYROSCOPE_PROFILER_ALLOC
              value: 32k
            - name: PYROSCOPE_PROFILER_LOCK
              value: 10ms
            - name: PYROSCOPE_SERVER_ADDRESS
              value: 'http://172.16.15.161:30424'
            - name: PYROSCOPE_LABELS
              value: 'env=test,zone=cloud,podname=$(POD_NAME)'
          image: 'xxxxxx/cpaas-test/cpaas-msg-hub:v1.8.3-8eecaaff295'
          name: cpaas-msg-hub
      initContainers:
        - command:
            - sh
            - '-c'
            - cp /opt/pyroscope.jar /shared-data/pyroscope/
          image: 'xwharbor.wxchina.com/cpaas/pyroscope:v2.1.2'
          name: pyroscope
          volumeMounts:
            - mountPath: /shared-data/pyroscope
              name: pyroscope
      volumes:
        - emptyDir: {}
          name: pyroscope


```
